{"start": 1523262101601, "historyId": "ae3b472d7595459a20e0469e7ce9ae96", "labels": [{"value": "testsuite2", "name": "feature"}, {"value": "testcass2", "name": "story"}, {"value": "testcass3", "name": "story"}, {"value": "testcass4", "name": "story"}, {"value": "DESKTOP-5PN9VPJ", "name": "host"}, {"value": "18440-Thread-1", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "test_demo1", "name": "package"}], "steps": [{"start": 1523262101601, "status": "passed", "stop": 1523262101601, "name": "步骤一"}, {"start": 1523262101601, "status": "passed", "stop": 1523262101601, "name": "步骤二"}, {"start": 1523262101601, "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"E:\\Nahsor\\test_demo1.py\", line 31, in test_bar2\n    assert False\n"}, "stop": 1523262101608, "status": "failed", "attachments": [{"source": "a960389c-f467-4f08-8e46-ba39e541da21-attachment.attach", "name": "具体内容"}], "name": "步骤三"}], "stop": 1523262101609, "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo1.TestBar object at 0x000002E5DCA97828>\n\n    @allure.title(\"测试报告2\")\n    def test_bar2(self):\n        with allure.step(\"步骤一\"):\n            assert True\n        with allure.step(\"步骤二\"):\n            assert True\n        with allure.step(\"步骤三\"):\n            allure.attach('失败的步骤', '具体内容')\n>           assert False\nE           assert False\n\ntest_demo1.py:31: AssertionError"}, "status": "failed", "uuid": "b74b2bc2-6338-472d-9bfe-12c2f0aac369", "name": "测试报告2", "fullName": "test_demo1.TestBar#test_bar2"}