{"stop": 1523251923599, "uuid": "a54765de-1c26-427d-8f7b-0797eb04a15b", "start": 1523251923595, "name": "测试报告2", "status": "failed", "historyId": "ae3b472d7595459a20e0469e7ce9ae96", "fullName": "test_demo1.TestBar#test_bar2", "labels": [{"value": "testsuite2", "name": "feature"}, {"value": "testcass2", "name": "story"}, {"value": "testcass3", "name": "story"}, {"value": "testcass4", "name": "story"}, {"value": "DESKTOP-5PN9VPJ", "name": "host"}, {"value": "11172-Thread-1", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "test_demo1", "name": "package"}], "statusDetails": {"trace": "self = <test_demo1.TestBar object at 0x0000019C885626D8>\n\n    @allure.title(\"测试报告2\")\n    def test_bar2(self):\n        with allure.step(\"步骤一\"):\n            assert True\n        with allure.step(\"步骤二\"):\n            assert True\n        with allure.step(\"步骤三\"):\n            allure.attach('失败的步骤', '具体内容')\n>           assert False\nE           assert False\n\ntest_demo1.py:35: AssertionError", "message": "AssertionError: assert False"}, "steps": [{"stop": 1523251923596, "start": 1523251923596, "status": "passed", "name": "步骤一"}, {"stop": 1523251923596, "start": 1523251923596, "status": "passed", "name": "步骤二"}, {"stop": 1523251923598, "start": 1523251923596, "name": "步骤三", "status": "failed", "attachments": [{"source": "2b33bba4-67a0-4269-a599-1e8dfe9fcf51-attachment.attach", "name": "具体内容"}], "statusDetails": {"trace": "  File \"E:\\Nahsor\\test_demo1.py\", line 35, in test_bar2\n    assert False\n", "message": "AssertionError: assert False\n"}}]}